### ISSUE TITLE
write a similar dsl for testing the store

### ISSUE THREAD

**Issue by dzfranklin** [dzfranklin/plantopo#62]
and move the layer false collision case there, as it's a failure at a lower level. session scenarios are still useful for other things I think

```yaml
GIVEN:
    lset:
        l1:
            id: l1
            idx: O
        l2:
            id: l2
WHEN:
    l1:
        id: l1
        idx: null
THEN:
    lset:
        l1:
            id: l1
            idx: null
        l2:
            id: l2
            idx: null
```

which we can just parse as yaml
